using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Operations;

namespace Jeomseon.Unity.Ownership.CodeGen
{
    [Generator]
    public sealed class ManagedResourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) => context.RegisterForSyntaxNotifications(() => new Receiver());

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is Receiver receiver)) return;
            var fields = receiver.Fields.Select(field => context.Compilation.GetSemanticModel(field.SyntaxTree).GetDeclaredSymbol(field))
                .OfType<IFieldSymbol>().Select(FieldInfo.Create).Where(info => info.Kind != ManagedKind.None);
            foreach (var group in fields.GroupBy(info => info.Field.ContainingType))
            {
                var type = group.Key;
                if (!OwnershipSymbols.IsSupportedOwner(type) || !OwnershipSymbols.IsPartial(type)) continue;
                var validFields = group.Where(info => info.IsValid).ToArray();
                if (validFields.Length > 0) context.AddSource(GetHintName(type), Generate(type, validFields));
            }
        }

        private static string Generate(INamedTypeSymbol type, IReadOnlyList<FieldInfo> fields)
        {
            var builder = new StringBuilder("// <auto-generated />\n#nullable disable\n");
            var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
            if (ns != null) builder.Append("namespace ").Append(ns).Append("\n{\n");
            var parents = new Stack<INamedTypeSymbol>();
            for (var parent = type.ContainingType; parent != null; parent = parent.ContainingType) parents.Push(parent);
            foreach (var parent in parents) { AppendTypeHeader(builder, parent); builder.Append("\n{\n"); }
            AppendTypeHeader(builder, type);
            builder.Append("\n{\n");
            foreach (var field in fields) GenerateField(builder, field);
            builder.Append("}\n");
            foreach (var unused in parents) builder.Append("}\n");
            if (ns != null) builder.Append("}\n");
            return builder.ToString();
        }

        private static void GenerateField(StringBuilder builder, FieldInfo info)
        {
            if (info.Kind == ManagedKind.GenericHandle) { GenerateGenericHandle(builder, info); return; }
            var field = info.Field;
            var property = OwnershipSymbols.GetPropertyName(field.Name);
            var rawType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var suffix = field.Name.TrimStart('_');
            var resource = "__ownershipResource_" + suffix;
            var registration = "__ownershipRegistration_" + suffix;
            var exchange = "__Exchange" + property;
            builder.Append("private global::System.IDisposable ").Append(resource).Append(";\n")
                .Append("private global::System.IDisposable ").Append(registration).Append(";\n")
                .Append("public ").Append(rawType).Append(' ').Append(property).Append(" => ").Append(field.Name).Append(";\n");
            if (info.Kind == ManagedKind.AddressableCollection)
            {
                var elementType = info.ValueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var collectionLease = "global::Jeomseon.Unity.Addressables.AddressableAssetCollectionLease<" + elementType + ">";
                GenerateSetter(builder, property, collectionLease, "Assets", exchange);
                builder.Append("public ").Append(collectionLease).Append(" Retain").Append(property).Append("()\n{\n")
                    .Append("var lease = ").Append(resource).Append(" as ").Append(collectionLease).Append(";\n")
                    .Append("if (lease == null || !lease.IsValid) throw new global::System.InvalidOperationException(\"The managed collection does not contain a retainable collection lease.\");\n")
                    .Append("return lease.Retain();\n}\n")
                    .Append("public ").Append(collectionLease).Append(" Take").Append(property).Append("() => __Take").Append(property).Append('<').Append(collectionLease).Append(">();\n");
            }
            else if (info.Kind == ManagedKind.AddressableAsset)
            {
                var assetLease = "global::Jeomseon.Unity.Addressables.AddressableAssetLease<" + rawType + ">";
                GenerateSetter(builder, property, assetLease, "Asset", exchange);
                builder.Append("public ").Append(assetLease).Append(" Retain").Append(property).Append("()\n{\n")
                    .Append("var lease = ").Append(resource).Append(" as ").Append(assetLease).Append(";\n")
                    .Append("if (lease == null || !lease.IsValid) throw new global::System.InvalidOperationException(\"The managed asset does not contain a retainable asset lease.\");\n")
                    .Append("return lease.Retain();\n}\n");
                if (OwnershipSymbols.IsType(field.Type, "UnityEngine.GameObject"))
                {
                    builder.Append("public ").Append(assetLease).Append(" Take").Append(property).Append("AssetLease() => __Take").Append(property).Append('<').Append(assetLease).Append(">();\n");
                    GenerateSetter(builder, property, "global::Jeomseon.Unity.Addressables.AddressableInstanceHandle", "Instance", exchange);
                    builder.Append("public global::Jeomseon.Unity.Addressables.AddressableInstanceHandle Take").Append(property)
                        .Append("InstanceHandle() => __Take").Append(property).Append("<global::Jeomseon.Unity.Addressables.AddressableInstanceHandle>();\n");
                }
                else
                    builder.Append("public ").Append(assetLease).Append(" Take").Append(property).Append("() => __Take").Append(property).Append('<').Append(assetLease).Append(">();\n");
            }
            else if (OwnershipSymbols.IsType(field.Type, "UnityEngine.GameObject"))
            {
                GenerateSetter(builder, property, "global::Jeomseon.Unity.GameObjectPooling.Ownership.PooledGameObjectLease", "Value", exchange);
                builder.Append("public global::Jeomseon.Unity.GameObjectPooling.Ownership.PooledGameObjectLease Take").Append(property)
                    .Append("() => __Take").Append(property).Append("<global::Jeomseon.Unity.GameObjectPooling.Ownership.PooledGameObjectLease>();\n");
            }
            else
            {
                GenerateSetter(builder, property, "global::Jeomseon.Unity.GameObjectPooling.Ownership.PooledInstanceLease<" + rawType + ">", "Value", exchange);
                builder.Append("public global::Jeomseon.Unity.GameObjectPooling.Ownership.PooledInstanceLease<").Append(rawType).Append("> Take").Append(property)
                    .Append("() => __Take").Append(property).Append("<global::Jeomseon.Unity.GameObjectPooling.Ownership.PooledInstanceLease<").Append(rawType).Append(">>();\n");
            }
            builder.Append("public void Clear").Append(property).Append("() => ").Append(exchange).Append("(null, default, false);\n")
                .Append("private TOwned __Take").Append(property).Append("<TOwned>() where TOwned : class, global::System.IDisposable\n{\n")
                .Append("if (").Append(resource).Append(" == null) return null;\n")
                .Append("var owned = ").Append(resource).Append(" as TOwned;\n")
                .Append("if (owned == null) throw new global::System.InvalidOperationException(\"The managed resource is owned by a different lease or handle type.\");\n")
                .Append(registration).Append("?.Dispose(); ").Append(registration).Append(" = null; ").Append(resource).Append(" = null; ").Append(field.Name).Append(" = default;\n")
                .Append("return owned;\n}\n")
                .Append("private void ").Append(exchange).Append("(global::System.IDisposable resource, ").Append(rawType).Append(" value, bool isValid)\n{\n")
                .Append("if (global::System.Object.ReferenceEquals(").Append(resource).Append(", resource)) return;\n")
                .Append("if (resource != null && !isValid) throw new global::System.ArgumentException(\"The ownership resource must be valid.\", nameof(resource));\n")
                .Append("var nextRegistration = resource == null ? null : global::Jeomseon.Unity.Ownership.OwnershipLifetimeHost.GetOrAdd(this).Track(resource);\n")
                .Append("var previousResource = ").Append(resource).Append("; var previousRegistration = ").Append(registration).Append(";\n")
                .Append(field.Name).Append(" = value; ").Append(resource).Append(" = resource; ").Append(registration).Append(" = nextRegistration;\n")
                .Append("previousRegistration?.Dispose(); previousResource?.Dispose();\n}\n");
        }

        private static void GenerateSetter(StringBuilder builder, string property, string resourceType, string member, string exchange) =>
            builder.Append("public void Set").Append(property).Append('(').Append(resourceType).Append(" value) => ").Append(exchange)
                .Append("(value, value == null ? default : value.").Append(member).Append(", value != null && value.IsValid);\n");

        private static void GenerateGenericHandle(StringBuilder builder, FieldInfo info)
        {
            var field = info.Field;
            var property = OwnershipSymbols.GetPropertyName(field.Name);
            var handleType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var valueType = info.ValueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var registration = "__ownershipRegistration_" + field.Name.TrimStart('_');
            builder.Append("private global::System.IDisposable ").Append(registration).Append(";\n")
                .Append("public ").Append(valueType).Append(' ').Append(property).Append(" => ").Append(field.Name).Append(" != null && ").Append(field.Name).Append(".IsValid ? ").Append(field.Name).Append(".Value : default;\n")
                .Append("public void Set").Append(property).Append('(').Append(handleType).Append(" value)\n{\n")
                .Append("if (global::System.Object.ReferenceEquals(").Append(field.Name).Append(", value)) return;\n")
                .Append("if (value != null && !value.IsValid) throw new global::System.ArgumentException(\"The ownership handle must be valid.\", nameof(value));\n")
                .Append("var nextRegistration = value == null ? null : global::Jeomseon.Unity.Ownership.OwnershipLifetimeHost.GetOrAdd(this).Track(value);\n")
                .Append("var previous = ").Append(field.Name).Append("; var previousRegistration = ").Append(registration).Append(";\n")
                .Append(field.Name).Append(" = value; ").Append(registration).Append(" = nextRegistration;\n")
                .Append("previousRegistration?.Dispose(); previous?.Dispose();\n}\n")
                .Append("public void Clear").Append(property).Append("() => Set").Append(property).Append("(null);\n")
                .Append("public ").Append(handleType).Append(" Take").Append(property).Append("()\n{\n")
                .Append("var owned = ").Append(field.Name).Append("; if (owned == null) return null;\n")
                .Append(registration).Append("?.Dispose(); ").Append(registration).Append(" = null; ").Append(field.Name).Append(" = null; return owned;\n}\n");
        }

        private static void AppendTypeHeader(StringBuilder builder, INamedTypeSymbol type)
        {
            builder.Append("partial class ").Append(type.Name);
            if (type.TypeParameters.Length > 0) builder.Append('<').Append(string.Join(", ", type.TypeParameters.Select(p => p.Name))).Append('>');
        }

        private static string GetHintName(INamedTypeSymbol type) => type.ToDisplayString().Replace('<', '_').Replace('>', '_').Replace('.', '_') + ".Ownership.g.cs";

        private sealed class Receiver : ISyntaxReceiver
        {
            public readonly List<VariableDeclaratorSyntax> Fields = new List<VariableDeclaratorSyntax>();
            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is FieldDeclarationSyntax declaration && declaration.AttributeLists.Count > 0) Fields.AddRange(declaration.Declaration.Variables);
            }
        }

        private readonly struct FieldInfo
        {
            private FieldInfo(IFieldSymbol field, ManagedKind kind, ITypeSymbol valueType, bool valid) { Field = field; Kind = kind; ValueType = valueType; IsValid = valid; }
            public IFieldSymbol Field { get; }
            public ManagedKind Kind { get; }
            public ITypeSymbol ValueType { get; }
            public bool IsValid { get; }
            public static FieldInfo Create(IFieldSymbol field)
            {
                var kind = OwnershipSymbols.GetManagedKind(field);
                if (kind == ManagedKind.AddressableAsset) return new FieldInfo(field, kind, field.Type, OwnershipSymbols.DerivesFrom(field.Type, "UnityEngine.Object"));
                if (kind == ManagedKind.AddressableCollection)
                {
                    var elementType = OwnershipSymbols.GetReadOnlyListElementType(field.Type);
                    return new FieldInfo(field, kind, elementType, elementType != null && OwnershipSymbols.DerivesFrom(elementType, "UnityEngine.Object"));
                }
                if (kind == ManagedKind.PooledObject) return new FieldInfo(field, kind, field.Type, OwnershipSymbols.DerivesFrom(field.Type, "UnityEngine.Component") || OwnershipSymbols.IsType(field.Type, "UnityEngine.GameObject"));
                var valueType = OwnershipSymbols.GetHandleValueType(field.Type);
                return new FieldInfo(field, kind, valueType, valueType != null);
            }
        }
    }

    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public sealed class ManagedResourceAnalyzer : DiagnosticAnalyzer
    {
        private static readonly DiagnosticDescriptor PartialRule = new DiagnosticDescriptor("JMO1010", "Managed resource owner must be partial", "Type '{0}' must be partial to use a managed resource attribute", "Ownership", DiagnosticSeverity.Error, true);
        private static readonly DiagnosticDescriptor TypeRule = new DiagnosticDescriptor("JMO1011", "Managed resource field type is unsupported", "Field '{0}' has a type that is not supported by its managed resource attribute", "Ownership", DiagnosticSeverity.Error, true);
        private static readonly DiagnosticDescriptor OwnerRule = new DiagnosticDescriptor("JMO1012", "Managed resource owner must be a Unity component", "Type '{0}' must derive from UnityEngine.Component for automatic lifetime hosting", "Ownership", DiagnosticSeverity.Error, true);
        private static readonly DiagnosticDescriptor DoesNotCaptureRule = new DiagnosticDescriptor("JMO1013", "DoesNotCapture contract is violated", "Parameter '{0}' is marked DoesNotCapture but is stored, returned, or captured", "Ownership", DiagnosticSeverity.Error, true);
        private static readonly DiagnosticDescriptor BorrowedRule = new DiagnosticDescriptor("JMO1020", "Generated managed resource value is borrowed", "Field '{0}' is released automatically on replacement or owner destruction; generated value '{1}' is borrowed and must not outlive its owner", "Ownership", DiagnosticSeverity.Warning, true);
        private static readonly DiagnosticDescriptor PersistentEscapeRule = new DiagnosticDescriptor("JMO1021", "Borrowed managed resource escapes to persistent storage", "Borrowed value '{0}' is stored in field or property '{1}'; retain or transfer ownership before storing it", "Ownership", DiagnosticSeverity.Warning, true);
        private static readonly DiagnosticDescriptor ReturnEscapeRule = new DiagnosticDescriptor("JMO1022", "Borrowed managed resource escapes through return", "Borrowed value '{0}' is returned from this method; retain or transfer ownership before returning it", "Ownership", DiagnosticSeverity.Warning, true);
        private static readonly DiagnosticDescriptor CaptureEscapeRule = new DiagnosticDescriptor("JMO1023", "Borrowed managed resource may outlive its owner", "Borrowed value '{0}' is captured or stored in a persistent collection; retain or transfer ownership first", "Ownership", DiagnosticSeverity.Warning, true);
        private static readonly DiagnosticDescriptor AwaitEscapeRule = new DiagnosticDescriptor("JMO1024", "Borrowed managed resource crosses an await boundary", "Borrowed local '{0}' is used after await; retain or transfer ownership before awaiting", "Ownership", DiagnosticSeverity.Warning, true);
        private static readonly DiagnosticDescriptor CallEscapeRule = new DiagnosticDescriptor("JMO1025", "Borrowed managed resource is passed to a capturing parameter", "Borrowed value '{0}' is passed to parameter '{1}', which may store or return it; retain or transfer ownership first", "Ownership", DiagnosticSeverity.Warning, true);
        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(PartialRule, TypeRule, OwnerRule, DoesNotCaptureRule, BorrowedRule, PersistentEscapeRule, ReturnEscapeRule, CaptureEscapeRule, AwaitEscapeRule, CallEscapeRule);
        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterSymbolAction(AnalyzeField, SymbolKind.Field);
            context.RegisterSyntaxNodeAction(AnalyzeAssignment, SyntaxKind.SimpleAssignmentExpression);
            context.RegisterSyntaxNodeAction(AnalyzeReturn, SyntaxKind.ReturnStatement, SyntaxKind.ArrowExpressionClause);
            context.RegisterSyntaxNodeAction(AnalyzeCapture, SyntaxKind.SimpleMemberAccessExpression, SyntaxKind.IdentifierName);
            context.RegisterSyntaxNodeAction(AnalyzeAwait, SyntaxKind.AwaitExpression);
            context.RegisterCompilationStartAction(startContext =>
            {
                var captureCache = new ConcurrentDictionary<IParameterSymbol, bool>(SymbolEqualityComparer.Default);
                startContext.RegisterSymbolAction(symbolContext => AnalyzeParameter(symbolContext, captureCache), SymbolKind.Parameter);
                startContext.RegisterSyntaxNodeAction(nodeContext => AnalyzeInvocation(nodeContext, captureCache), SyntaxKind.InvocationExpression);
            });
        }
        private static void AnalyzeField(SymbolAnalysisContext context)
        {
            var field = (IFieldSymbol)context.Symbol;
            var kind = OwnershipSymbols.GetManagedKind(field);
            if (kind == ManagedKind.None) return;
            var location = field.Locations.FirstOrDefault();
            var partial = OwnershipSymbols.IsPartial(field.ContainingType);
            var owner = OwnershipSymbols.IsSupportedOwner(field.ContainingType);
            var valid = kind == ManagedKind.AddressableAsset ? OwnershipSymbols.DerivesFrom(field.Type, "UnityEngine.Object")
                : kind == ManagedKind.AddressableCollection ? IsValidCollection(field.Type)
                : kind == ManagedKind.PooledObject ? OwnershipSymbols.DerivesFrom(field.Type, "UnityEngine.Component") || OwnershipSymbols.IsType(field.Type, "UnityEngine.GameObject")
                : OwnershipSymbols.GetHandleValueType(field.Type) != null;
            if (!partial) context.ReportDiagnostic(Diagnostic.Create(PartialRule, location, field.ContainingType.Name));
            if (!valid) context.ReportDiagnostic(Diagnostic.Create(TypeRule, location, field.Name));
            if (!owner) context.ReportDiagnostic(Diagnostic.Create(OwnerRule, location, field.ContainingType.Name));
            if (partial && valid && owner) context.ReportDiagnostic(Diagnostic.Create(BorrowedRule, location, field.Name, OwnershipSymbols.GetPropertyName(field.Name)));
        }

        private static bool IsValidCollection(ITypeSymbol type)
        {
            var elementType = OwnershipSymbols.GetReadOnlyListElementType(type);
            return elementType != null && OwnershipSymbols.DerivesFrom(elementType, "UnityEngine.Object");
        }

        private static void AnalyzeParameter(SymbolAnalysisContext context, ConcurrentDictionary<IParameterSymbol, bool> captureCache)
        {
            var parameter = (IParameterSymbol)context.Symbol;
            if (!HasDoesNotCapture(parameter)) return;
            if (!ParameterMayCaptureCached(parameter, context.Compilation, context.CancellationToken, captureCache)) return;
            context.ReportDiagnostic(Diagnostic.Create(DoesNotCaptureRule, parameter.Locations.FirstOrDefault(), parameter.Name));
        }

        private static void AnalyzeAssignment(SyntaxNodeAnalysisContext context)
        {
            var assignment = (AssignmentExpressionSyntax)context.Node;
            if (!TryGetBorrowedName(assignment.Right, context.SemanticModel, out var borrowed)) return;
            var destination = context.SemanticModel.GetSymbolInfo(assignment.Left, context.CancellationToken).Symbol;
            if (!(destination is IFieldSymbol) && !(destination is IPropertySymbol)) return;
            context.ReportDiagnostic(Diagnostic.Create(PersistentEscapeRule, assignment.Right.GetLocation(), borrowed, destination.Name));
        }

        private static void AnalyzeReturn(SyntaxNodeAnalysisContext context)
        {
            ExpressionSyntax expression = context.Node is ReturnStatementSyntax statement ? statement.Expression
                : ((ArrowExpressionClauseSyntax)context.Node).Expression;
            if (!TryGetBorrowedName(expression, context.SemanticModel, out var borrowed)) return;
            context.ReportDiagnostic(Diagnostic.Create(ReturnEscapeRule, expression.GetLocation(), borrowed));
        }

        private static void AnalyzeInvocation(SyntaxNodeAnalysisContext context, ConcurrentDictionary<IParameterSymbol, bool> captureCache)
        {
            var invocation = (InvocationExpressionSyntax)context.Node;
            if (invocation.Expression is MemberAccessExpressionSyntax member && member.Name.Identifier.ValueText == "Add")
            {
                var receiver = context.SemanticModel.GetSymbolInfo(member.Expression, context.CancellationToken).Symbol;
                if (receiver is IFieldSymbol || receiver is IPropertySymbol)
                    foreach (var argument in invocation.ArgumentList.Arguments)
                        if (TryGetBorrowedName(argument.Expression, context.SemanticModel, out var borrowed))
                            context.ReportDiagnostic(Diagnostic.Create(CaptureEscapeRule, argument.Expression.GetLocation(), borrowed));
            }

            if (!(context.SemanticModel.GetOperation(invocation, context.CancellationToken) is IInvocationOperation operation)) return;
            foreach (var argument in operation.Arguments)
            {
                if (argument.Parameter == null || HasDoesNotCapture(argument.Parameter)) continue;
                var argumentExpression = argument.Syntax is ArgumentSyntax syntax ? syntax.Expression : argument.Value.Syntax as ExpressionSyntax;
                if (!TryGetBorrowedName(argumentExpression, context.SemanticModel, out var borrowed)) continue;
                if (!ParameterMayCaptureCached(argument.Parameter, context.Compilation, context.CancellationToken, captureCache)) continue;
                context.ReportDiagnostic(Diagnostic.Create(CallEscapeRule, argument.Syntax.GetLocation(), borrowed, argument.Parameter.Name));
            }
        }

        private static bool HasDoesNotCapture(IParameterSymbol parameter) => parameter.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() == "Jeomseon.Unity.Ownership.DoesNotCaptureAttribute");

        private static bool ParameterMayCaptureCached(IParameterSymbol parameter, Compilation compilation, System.Threading.CancellationToken cancellationToken, ConcurrentDictionary<IParameterSymbol, bool> captureCache) =>
            captureCache.GetOrAdd(parameter, unused => ParameterMayCapture(parameter, compilation, cancellationToken));

        private static bool ParameterMayCapture(IParameterSymbol parameter, Compilation compilation, System.Threading.CancellationToken cancellationToken)
        {
            foreach (var syntaxReference in parameter.ContainingSymbol.DeclaringSyntaxReferences)
            {
                var declaration = syntaxReference.GetSyntax(cancellationToken);
                var model = compilation.GetSemanticModel(declaration.SyntaxTree);
                foreach (var assignment in declaration.DescendantNodes().OfType<AssignmentExpressionSyntax>())
                {
                    var destination = model.GetSymbolInfo(assignment.Left, cancellationToken).Symbol;
                    if ((destination is IFieldSymbol || destination is IPropertySymbol) &&
                        DependsOnParameter(assignment.Right, parameter, model, cancellationToken, new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default))) return true;
                }
                foreach (var statement in declaration.DescendantNodes().OfType<ReturnStatementSyntax>())
                    if (DependsOnParameter(statement.Expression, parameter, model, cancellationToken, new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default))) return true;
                if (declaration is MethodDeclarationSyntax method && method.ExpressionBody != null &&
                    DependsOnParameter(method.ExpressionBody.Expression, parameter, model, cancellationToken, new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default))) return true;
                foreach (var nested in declaration.DescendantNodes().OfType<InvocationExpressionSyntax>())
                {
                    if (!(nested.Expression is MemberAccessExpressionSyntax nestedMember) || nestedMember.Name.Identifier.ValueText != "Add") continue;
                    var receiver = model.GetSymbolInfo(nestedMember.Expression, cancellationToken).Symbol;
                    if (!(receiver is IFieldSymbol) && !(receiver is IPropertySymbol)) continue;
                    if (nested.ArgumentList.Arguments.Any(argument => DependsOnParameter(argument.Expression, parameter, model, cancellationToken, new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default)))) return true;
                }
                foreach (var anonymous in declaration.DescendantNodes().OfType<AnonymousFunctionExpressionSyntax>())
                    if (anonymous.DescendantNodes().OfType<ExpressionSyntax>().Any(expression => DependsOnParameter(expression, parameter, model, cancellationToken, new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default)))) return true;
            }
            return false;
        }

        private static bool DependsOnParameter(ExpressionSyntax expression, IParameterSymbol parameter, SemanticModel model, System.Threading.CancellationToken cancellationToken, HashSet<ILocalSymbol> visited)
        {
            if (expression == null) return false;
            foreach (var identifier in expression.DescendantNodesAndSelf().OfType<IdentifierNameSyntax>())
            {
                var symbol = model.GetSymbolInfo(identifier, cancellationToken).Symbol;
                if (SymbolEqualityComparer.Default.Equals(symbol, parameter)) return true;
                if (!(symbol is ILocalSymbol local) || !visited.Add(local)) continue;
                var declarator = local.DeclaringSyntaxReferences.Select(reference => reference.GetSyntax(cancellationToken)).OfType<VariableDeclaratorSyntax>().FirstOrDefault();
                if (declarator?.Initializer != null && DependsOnParameter(declarator.Initializer.Value, parameter, model, cancellationToken, visited)) return true;
                foreach (var assignment in expression.SyntaxTree.GetRoot(cancellationToken).DescendantNodes().OfType<AssignmentExpressionSyntax>())
                    if (assignment.SpanStart < identifier.SpanStart && SymbolEqualityComparer.Default.Equals(model.GetSymbolInfo(assignment.Left, cancellationToken).Symbol, local) &&
                        DependsOnParameter(assignment.Right, parameter, model, cancellationToken, visited)) return true;
            }
            return false;
        }

        private static void AnalyzeCapture(SyntaxNodeAnalysisContext context)
        {
            var expression = context.Node as ExpressionSyntax;
            if (expression == null || !expression.Ancestors().Any(node => node is AnonymousFunctionExpressionSyntax)) return;
            if (expression.Parent is MemberAccessExpressionSyntax parent && parent.Expression == expression) return;
            if (expression.Parent is MemberAccessExpressionSyntax namedParent && namedParent.Name == expression) return;
            if (!TryGetBorrowedName(expression, context.SemanticModel, out var borrowed)) return;
            context.ReportDiagnostic(Diagnostic.Create(CaptureEscapeRule, expression.GetLocation(), borrowed));
        }

        private static bool TryGetBorrowedName(ExpressionSyntax expression, SemanticModel model, out string name)
            => TryGetBorrowedName(expression, model, new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default), out name);

        private static bool TryGetBorrowedName(ExpressionSyntax expression, SemanticModel model, HashSet<ILocalSymbol> visited, out string name)
        {
            name = null;
            if (expression == null) return false;
            expression = expression is ParenthesizedExpressionSyntax parentheses ? parentheses.Expression : expression;
            if (expression is CastExpressionSyntax cast)
                return TryGetBorrowedName(cast.Expression, model, visited, out name);
            if (expression is ConditionalExpressionSyntax conditional)
                return TryEither(conditional.WhenTrue, conditional.WhenFalse, model, visited, out name);
            if (expression is BinaryExpressionSyntax binary && binary.IsKind(SyntaxKind.CoalesceExpression))
                return TryEither(binary.Left, binary.Right, model, visited, out name);
            var symbol = model.GetSymbolInfo(expression).Symbol;
            if (symbol is IPropertySymbol property && property.DeclaringSyntaxReferences.Length > 0)
            {
                foreach (var field in property.ContainingType.GetMembers().OfType<IFieldSymbol>())
                {
                    if (OwnershipSymbols.GetManagedKind(field) == ManagedKind.None) continue;
                    if (OwnershipSymbols.GetPropertyName(field.Name) != property.Name) continue;
                    name = property.Name;
                    return true;
                }
            }

            if (!(symbol is ILocalSymbol local) || !visited.Add(local)) return false;
            return TryGetBorrowedLocalBefore(local, expression.SpanStart, expression, model, visited, out name);
        }

        private static bool TryGetBorrowedLocalBefore(ILocalSymbol local, int position, SyntaxNode reference, SemanticModel model, HashSet<ILocalSymbol> visited, out string name)
        {
            name = null;
            var assignments = reference.SyntaxTree.GetRoot().DescendantNodes()
                .OfType<AssignmentExpressionSyntax>()
                .Where(candidate => candidate.SpanStart < position &&
                    SymbolEqualityComparer.Default.Equals(model.GetSymbolInfo(candidate.Left).Symbol, local))
                .OrderByDescending(candidate => candidate.SpanStart)
                .ToArray();
            var useBlock = reference.AncestorsAndSelf().OfType<BlockSyntax>().FirstOrDefault();
            var dominatingAssignment = assignments.FirstOrDefault(candidate =>
                candidate.Ancestors().OfType<BlockSyntax>().FirstOrDefault() == useBlock);
            if (dominatingAssignment != null)
                return TryGetBorrowedName(dominatingAssignment.Right, model, visited, out name);
            foreach (var assignment in assignments)
            {
                var branchVisited = new HashSet<ILocalSymbol>(visited, SymbolEqualityComparer.Default);
                if (TryGetBorrowedName(assignment.Right, model, branchVisited, out name)) return true;
            }
            var declarator = local.DeclaringSyntaxReferences.Select(reference => reference.GetSyntax())
                .OfType<VariableDeclaratorSyntax>().FirstOrDefault();
            if (declarator?.Initializer != null && declarator.SpanStart < position)
                return TryGetBorrowedName(declarator.Initializer.Value, model, visited, out name);
            return false;
        }

        private static bool TryEither(ExpressionSyntax first, ExpressionSyntax second, SemanticModel model, HashSet<ILocalSymbol> visited, out string name)
        {
            var firstVisited = new HashSet<ILocalSymbol>(visited, SymbolEqualityComparer.Default);
            if (TryGetBorrowedName(first, model, firstVisited, out name)) return true;
            var secondVisited = new HashSet<ILocalSymbol>(visited, SymbolEqualityComparer.Default);
            return TryGetBorrowedName(second, model, secondVisited, out name);
        }

        private static void AnalyzeAwait(SyntaxNodeAnalysisContext context)
        {
            var awaitExpression = (AwaitExpressionSyntax)context.Node;
            var scope = awaitExpression.Ancestors().FirstOrDefault(node => node is BaseMethodDeclarationSyntax || node is LocalFunctionStatementSyntax || node is AnonymousFunctionExpressionSyntax);
            if (scope == null) return;
            var reported = new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default);
            foreach (var identifier in scope.DescendantNodes().OfType<IdentifierNameSyntax>().Where(node => node.SpanStart > awaitExpression.Span.End))
            {
                if (!(context.SemanticModel.GetSymbolInfo(identifier).Symbol is ILocalSymbol local)) continue;
                if (identifier.AncestorsAndSelf().OfType<AssignmentExpressionSyntax>().Any(assignment => assignment.Left.Span.Contains(identifier.Span))) continue;
                if (!reported.Add(local)) continue;
                var assignedAfterAwait = scope.DescendantNodes().OfType<AssignmentExpressionSyntax>()
                    .Any(assignment => assignment.SpanStart > awaitExpression.Span.End && assignment.SpanStart < identifier.SpanStart &&
                        assignment.Ancestors().OfType<BlockSyntax>().FirstOrDefault() == identifier.Ancestors().OfType<BlockSyntax>().FirstOrDefault() &&
                        SymbolEqualityComparer.Default.Equals(context.SemanticModel.GetSymbolInfo(assignment.Left).Symbol, local));
                if (assignedAfterAwait) continue;
                var visited = new HashSet<ILocalSymbol>(SymbolEqualityComparer.Default) { local };
                if (!TryGetBorrowedLocalBefore(local, awaitExpression.SpanStart, awaitExpression, context.SemanticModel, visited, out var borrowed)) continue;
                context.ReportDiagnostic(Diagnostic.Create(AwaitEscapeRule, identifier.GetLocation(), local.Name));
            }
        }
    }

    internal enum ManagedKind { None, GenericHandle, AddressableAsset, AddressableCollection, PooledObject }

    internal static class OwnershipSymbols
    {
        private const string ManagedAttribute = "Jeomseon.Unity.Ownership.ManagedResourceAttribute";
        private const string ManagedAsset = "Jeomseon.Unity.Addressables.Ownership.ManagedAssetAttribute";
        private const string ManagedAssetCollection = "Jeomseon.Unity.Addressables.Ownership.ManagedAssetCollectionAttribute";
        private const string ManagedPooled = "Jeomseon.Unity.GameObjectPooling.Ownership.ManagedPooledObjectAttribute";
        private const string Handle = "Jeomseon.Unity.Ownership.IOwnershipHandle<T>";
        public static ManagedKind GetManagedKind(IFieldSymbol field)
        {
            foreach (var attribute in field.GetAttributes())
                for (var type = attribute.AttributeClass; type != null; type = type.BaseType)
                {
                    var name = type.ToDisplayString();
                    if (name == ManagedAsset) return ManagedKind.AddressableAsset;
                    if (name == ManagedAssetCollection) return ManagedKind.AddressableCollection;
                    if (name == ManagedPooled) return ManagedKind.PooledObject;
                    if (name == ManagedAttribute) return ManagedKind.GenericHandle;
                }
            return ManagedKind.None;
        }
        public static ITypeSymbol GetHandleValueType(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol named && named.OriginalDefinition.ToDisplayString() == Handle) return named.TypeArguments[0];
            return type.AllInterfaces.FirstOrDefault(i => i.OriginalDefinition.ToDisplayString() == Handle)?.TypeArguments[0];
        }
        public static ITypeSymbol GetReadOnlyListElementType(ITypeSymbol type)
        {
            if (!(type is INamedTypeSymbol named) || named.OriginalDefinition.ToDisplayString() != "System.Collections.Generic.IReadOnlyList<T>") return null;
            return named.TypeArguments[0];
        }
        public static bool IsType(ITypeSymbol type, string name) => type.ToDisplayString() == name;
        public static bool DerivesFrom(ITypeSymbol type, string name)
        {
            for (var current = type; current != null; current = current.BaseType) if (current.ToDisplayString() == name) return true;
            return false;
        }
        public static string GetPropertyName(string fieldName)
        {
            var name = fieldName.TrimStart('_');
            return name.Length == 0 ? "Resource" : char.ToUpperInvariant(name[0]) + name.Substring(1);
        }
        public static bool IsPartial(INamedTypeSymbol type)
        {
            for (var current = type; current != null; current = current.ContainingType)
                if (!current.DeclaringSyntaxReferences.All(r => ((TypeDeclarationSyntax)r.GetSyntax()).Modifiers.Any(SyntaxKind.PartialKeyword))) return false;
            return true;
        }
        public static bool IsSupportedOwner(INamedTypeSymbol type)
        {
            for (var current = type; current != null; current = current.BaseType) if (current.ToDisplayString() == "UnityEngine.Component") return true;
            return false;
        }
    }
}
